export const FEATURED_STATES = [
  { name: "Florida", slug: "florida", code: "FL", note: "Coastal travel and facility-specific credentialing" },
  { name: "Texas", slug: "texas", code: "TX", note: "Metro, regional, and multi-site planning" },
  { name: "California", slug: "california", code: "CA", note: "Licensing lead times and travel economics" },
  { name: "New York", slug: "new-york", code: "NY", note: "Metro and regional coverage planning" },
  { name: "North Carolina", slug: "north-carolina", code: "NC", note: "Charlotte and Triangle travel preferences" },
  { name: "Arizona", slug: "arizona", code: "AZ", note: "Calendar, housing, and travel planning" },
  { name: "Washington", slug: "washington", code: "WA", note: "Pacific Northwest licensing and travel context" },
] as const;

export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;
