import type { OpenJobDraft } from "./types";

/** Board jobs except D3 (updates the existing NC outpatient page) and V24 (unconfirmed). */
export const OPEN_JOB_DRAFTS: OpenJobDraft[] = [
  {
    slug: "kansas-western-non-invasive-cardiology-locum",
    state: "Kansas",
    stateSlug: "kansas",
    region: "Western Kansas",
    track: "non-invasive",
    kind: "direct",
    datePosted: "2026-07-30",
    need: "Inpatient non-invasive coverage with a seven-day-per-month minimum and call.",
    setting: "Inpatient non-invasive cardiology",
    schedule: "Seven days per month minimum",
    call: "Call during scheduled coverage",
    metaTitle: "Western KS Non-Invasive Cardiology Locum | 7 Days/Mo",
    angle:
      "This is a western Kansas inpatient block, not the existing 7-on/7-off Kansas nuclear assignment. The board asks for a smaller monthly footprint—seven days minimum—so it can fit physicians who already hold other blocks or an employed clinic week.",
  },
  {
    slug: "pennsylvania-northwestern-interventional-cardiology-locum",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    region: "Northwestern Pennsylvania",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-05-26",
    need: "Interventional coverage with call plus scheduled hours.",
    setting: "Interventional cardiology",
    schedule: "Scheduled clinical hours plus call",
    call: "Call in addition to scheduled hours",
    metaTitle: "NW Pennsylvania Interventional Cardiology Locum | Call",
    angle:
      "Northwestern Pennsylvania needs an interventionalist who can take call and still work scheduled hours—not a nights-only STEMI panel. Confirm cath-lab backup, activation rules, and whether clinic is part of the scheduled day before you accept.",
  },
  {
    slug: "pennsylvania-southwestern-interventional-cardiology-locum",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    region: "Southwestern Pennsylvania",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-08-22",
    need: "Holiday interventional coverage from December 31 through January 4, paying 1.3× on holidays.",
    setting: "Interventional cardiology holiday coverage",
    schedule: "December 31 through January 4",
    call: "Holiday interventional call during the coverage window",
    compensation: "1.3× pay on holidays during December 31–January 4 coverage",
    metaTitle: "SW Pennsylvania IC Locum | Holiday 1.3× Coverage",
    angle:
      "This southwestern Pennsylvania opening is a defined holiday window, not an open-ended monthly interventional contract. The 1.3× holiday rate applies to that December 31–January 4 block; ask us to confirm what is included in the multiplier before you travel.",
  },
  {
    slug: "florida-south-central-non-invasive-cardiology-locum",
    state: "Florida",
    stateSlug: "florida",
    region: "South-central Florida",
    track: "non-invasive",
    kind: "direct",
    datePosted: "2026-09-08",
    need: "Ongoing inpatient and outpatient non-invasive cardiology coverage.",
    setting: "Inpatient and outpatient non-invasive cardiology",
    schedule: "Ongoing mixed inpatient/outpatient coverage",
    call: "Confirm call expectations in writing before you accept",
    metaTitle: "South-Central Florida Non-Invasive Cardiology Locum",
    angle:
      "South-central Florida is recruiting mixed inpatient and outpatient non-invasive work on an ongoing basis. That is a different product than a one-week call-only block and a different specialty than the south-central Florida interventional opening.",
  },
  {
    slug: "north-carolina-central-interventional-cardiology-locum",
    state: "North Carolina",
    stateSlug: "north-carolina",
    region: "Central North Carolina",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-08-26",
    need: "Call-only interventional coverage, ongoing.",
    setting: "Interventional cardiology call coverage",
    schedule: "Ongoing call-only coverage",
    call: "Call only—no routine scheduled clinic described",
    metaTitle: "Central NC Interventional Cardiology Locum | Call Only",
    angle:
      "Central North Carolina is asking for interventional call only, not a weekday clinic plus STEMI mix. If you want protected daytime hours and no clinic panel, this is the NC interventional row to review—separate from the western North Carolina outpatient clinic job.",
  },
  {
    slug: "florida-south-central-interventional-cardiology-locum",
    state: "Florida",
    stateSlug: "florida",
    region: "South-central Florida",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-09-24",
    need: "Inpatient/outpatient interventional work plus call, one-week minimum.",
    setting: "Inpatient and outpatient interventional cardiology",
    schedule: "One-week minimum blocks",
    call: "Call in addition to inpatient/outpatient work",
    metaTitle: "South-Central Florida Interventional Cardiology Locum",
    angle:
      "Same south-central Florida region as the non-invasive opening, different specialty. The board wants mixed inpatient/outpatient interventional work plus call, with a one-week minimum rather than a same-day STEMI-only fill.",
  },
  {
    slug: "mississippi-southern-interventional-cardiology-locum",
    state: "Mississippi",
    stateSlug: "mississippi",
    region: "Southern Mississippi",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-09-17",
    need: "24-hour interventional call, sporadic dates, ongoing.",
    setting: "Interventional cardiology 24-hour call",
    schedule: "Sporadic dates, ongoing",
    call: "24-hour call",
    metaTitle: "Southern Mississippi IC Locum | 24-Hour Call",
    angle:
      "Southern Mississippi is staffing 24-hour interventional call on sporadic dates rather than a standing weekly clinic. That pattern can work for physicians who can take isolated call blocks without committing a full month of days.",
  },
  {
    slug: "arkansas-western-interventional-cardiology-locum",
    state: "Arkansas",
    stateSlug: "arkansas",
    region: "Western Arkansas",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-07-14",
    need: "Holiday coverage plus ongoing interventional call, paying 24-hour call rates.",
    setting: "Interventional cardiology holiday and ongoing call",
    schedule: "Holiday coverage plus ongoing call dates",
    call: "24-hour call; paying 24-hour call rates",
    compensation: "Paying 24-hour call rates for holiday coverage and ongoing call",
    metaTitle: "Western Arkansas IC Locum | 24-Hour Call Rates",
    angle:
      "Western Arkansas is paying 24-hour call rates for holiday coverage and ongoing call—not a daytime clinic guarantee. Ask us to confirm which hours count toward the 24-hour rate and how holiday dates sit next to the ongoing panel.",
  },
  {
    slug: "north-dakota-eastern-interventional-cardiology-locum",
    state: "North Dakota",
    stateSlug: "north-dakota",
    region: "Eastern North Dakota",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-08-15",
    need: "Ten days per month, nine-hour days plus call.",
    setting: "Interventional cardiology",
    schedule: "Ten days per month; nine-hour days",
    call: "Call in addition to nine-hour clinical days",
    metaTitle: "Eastern ND Interventional Cardiology Locum | 10 Days",
    angle:
      "Eastern North Dakota wants about ten interventional days a month with nine-hour days plus call. That is a denser monthly footprint than a one-week call-only job and a clearer daytime expectation than an unbounded STEMI panel.",
  },
  {
    slug: "new-mexico-southern-interventional-cardiology-locum",
    state: "New Mexico",
    stateSlug: "new-mexico",
    region: "Southern New Mexico",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-06-03",
    need: "Call-only interventional coverage with a one-week minimum.",
    setting: "Interventional cardiology call coverage",
    schedule: "One-week minimum",
    call: "Call only",
    metaTitle: "Southern New Mexico IC Locum | Call, 1-Week Min",
    angle:
      "Southern New Mexico is call-only interventional coverage with a one-week minimum. If you prefer not to pick up a standing clinic panel, this is closer to a defined call week than a mixed rounding-and-lab job.",
  },
  {
    slug: "alabama-northeastern-interventional-cardiology-locum",
    state: "Alabama",
    stateSlug: "alabama",
    region: "Northeastern Alabama",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-07-16",
    need: "Interventional call, ongoing with sporadic dates.",
    setting: "Interventional cardiology call coverage",
    schedule: "Ongoing coverage on sporadic dates",
    call: "Call",
    metaTitle: "NE Alabama Interventional Cardiology Locum | Call",
    angle:
      "Northeastern Alabama needs interventional call on an ongoing but sporadic calendar—different from the northwestern Alabama medical-leave call row. Share the weeks you can actually take so we do not present you for dates you cannot hold.",
  },
  {
    slug: "louisiana-southeastern-non-invasive-cardiology-locum",
    state: "Louisiana",
    stateSlug: "louisiana",
    region: "Southeastern Louisiana",
    track: "non-invasive",
    kind: "direct",
    datePosted: "2026-07-16",
    need: "Call plus inpatient call, ongoing with sporadic dates.",
    setting: "Non-invasive cardiology with call and inpatient call",
    schedule: "Ongoing coverage on sporadic dates",
    call: "Call plus inpatient call",
    metaTitle: "SE Louisiana Non-Invasive Cardiology Locum | Call",
    angle:
      "Southeastern Louisiana is not clinic-only. The board specified call plus inpatient call on sporadic dates, so candidates should be ready for hospital-side non-invasive work rather than a weekday office panel alone.",
  },
  {
    slug: "pennsylvania-southwestern-non-invasive-cardiology-locum",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    region: "Southwestern Pennsylvania",
    track: "non-invasive",
    kind: "direct",
    datePosted: "2026-09-23",
    need: "Monday-to-Monday inpatient rounding plus call.",
    setting: "Inpatient non-invasive cardiology rounding",
    schedule: "Monday-to-Monday inpatient rounding",
    call: "Call in addition to Monday-to-Monday rounding",
    metaTitle: "SW Pennsylvania Non-Invasive Locum | M–M Rounding",
    angle:
      "Southwestern Pennsylvania’s non-invasive row is a Monday-to-Monday inpatient rounding block plus call—not the holiday interventional window in the same region. If you want a defined hospital week rather than a clinic month, this is the PA non-invasive page.",
  },
  {
    slug: "mississippi-western-interventional-cardiology-locum",
    state: "Mississippi",
    stateSlug: "mississippi",
    region: "Western Mississippi",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-09-21",
    need: "Interventional coverage; a Mississippi license is required for October dates.",
    setting: "Interventional cardiology",
    schedule: "October dates require a current Mississippi license",
    call: "Confirm call scope in writing before you accept",
    extraRequirements: [
      "Active Mississippi medical license required for October dates",
    ],
    extraFaqs: [
      {
        q: "Do I already need a Mississippi license for this interventional locum?",
        a: "For the October dates on this western Mississippi opening, yes. A Mississippi license is required. If you would still need to license, ask us about later dates rather than assuming October is reachable.",
      },
    ],
    metaTitle: "Western MS Interventional Cardiology Locum | October",
    angle:
      "Western Mississippi is a separate interventional row from southern Mississippi’s 24-hour sporadic call job. The gating item here is licensure: October dates require an active Mississippi license now, not a plan to start the application after you inquire.",
  },
  {
    slug: "minnesota-northeastern-ep-cardiology-locum",
    state: "Minnesota",
    stateSlug: "minnesota",
    region: "Northeastern Minnesota",
    track: "electrophysiology",
    kind: "direct",
    datePosted: "2025-11-23",
    need: "Electrophysiology coverage two weeks per month, ongoing.",
    setting: "Electrophysiology",
    schedule: "Two weeks per month, ongoing",
    call: "Confirm EP call and lab backup in writing before you accept",
    metaTitle: "NE Minnesota Electrophysiology Locum | 2 Wks/Mo",
    angle:
      "Northeastern Minnesota wants recurring EP blocks at two weeks per month. Minnesota is not an IMLC shortcut for most physicians, so licensing time is part of whether this cadence is realistic. Ablation and device privileges are separate from a general cardiology license.",
  },
  {
    slug: "california-northwestern-interventional-cardiology-locum",
    state: "California",
    stateSlug: "california",
    region: "Northwestern California",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-08-26",
    need: "Interventional call coverage described as coverable.",
    setting: "Interventional cardiology call coverage",
    schedule: "Call coverage; dates confirmed with a consultant",
    call: "Call coverage",
    metaTitle: "NW California Interventional Cardiology Locum | Call",
    angle:
      "Northwestern California needs interventional call that the client described as coverable. California is not an IMLC pathway for most physicians, so an existing California license—or a realistic full-license timeline—matters more than compact speed.",
  },
  {
    slug: "wisconsin-east-central-ep-cardiology-locum",
    state: "Wisconsin",
    stateSlug: "wisconsin",
    region: "East-central Wisconsin",
    track: "electrophysiology",
    kind: "direct",
    datePosted: "2025-12-23",
    need: "Inpatient and outpatient electrophysiology plus call.",
    setting: "Inpatient and outpatient electrophysiology",
    schedule: "Mixed inpatient/outpatient EP coverage",
    call: "Call in addition to inpatient/outpatient EP work",
    metaTitle: "East-Central Wisconsin EP Locum | IP/OP + Call",
    angle:
      "East-central Wisconsin is mixed inpatient/outpatient EP plus call, not a two-week Minnesota-style block. Lab case mix, device follow-up, and call backup should be confirmed in writing; general cardiology privileges are not a substitute for EP privileges.",
  },
  {
    slug: "alabama-northwestern-interventional-cardiology-locum",
    state: "Alabama",
    stateSlug: "alabama",
    region: "Northwestern Alabama",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-09-10",
    need: "Call-only interventional coverage for medical leave.",
    setting: "Interventional cardiology medical-leave call coverage",
    schedule: "Medical-leave coverage; dates confirmed with a consultant",
    call: "Call only",
    metaTitle: "NW Alabama Interventional Cardiology Locum | Leave",
    angle:
      "Northwestern Alabama is medical-leave interventional call, not the northeastern Alabama sporadic ongoing call row. Leave coverage can start or end when the employed physician returns, so availability has to be checked before you hold dates.",
  },
  {
    slug: "indiana-northern-non-invasive-cardiology-locum",
    state: "Indiana",
    stateSlug: "indiana",
    region: "Northern Indiana",
    track: "non-invasive",
    kind: "direct",
    datePosted: "2026-09-17",
    need: "Clinic-only non-invasive coverage now, with inpatient work later.",
    setting: "Outpatient non-invasive cardiology (inpatient later)",
    schedule: "Clinic only at the start; inpatient coverage expected later",
    call: "Confirm whether clinic-only weeks include after-hours phone coverage",
    metaTitle: "Northern Indiana Non-Invasive Cardiology Locum | Clinic",
    angle:
      "Northern Indiana starts as clinic-only non-invasive work, with inpatient coverage expected later. If you only want office cardiology forever, say so when you inquire; if you can add inpatient later, that matches the board note.",
  },
  {
    slug: "kansas-northeastern-interventional-cardiology-locum",
    state: "Kansas",
    stateSlug: "kansas",
    region: "Northeastern Kansas",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-09-17",
    need: "Monday–Friday eight-hour days, 24-hour call, full-time interventional coverage. Confirm whether nuclear cardiology is part of the scope.",
    setting: "Full-time interventional cardiology",
    schedule: "Monday–Friday eight-hour days; full-time",
    call: "24-hour call",
    extraFaqs: [
      {
        q: "Does this northeastern Kansas interventional locum require nuclear cardiology?",
        a: "The board note included “NC.” We treat that as unverified—possibly nuclear cardiology—and confirm the actual scope with you before presentation. Do not assume nuclear is required or excluded until we check.",
      },
    ],
    metaTitle: "NE Kansas Interventional Cardiology Locum | Full-Time",
    angle:
      "Northeastern Kansas is a full-time Monday–Friday interventional job with eight-hour days and 24-hour call. It is not the western Kansas seven-day non-invasive block and not the existing Kansas 7-on/7-off nuclear inpatient page.",
  },
  {
    slug: "minnesota-north-central-interventional-cardiology-locum",
    state: "Minnesota",
    stateSlug: "minnesota",
    region: "North-central Minnesota",
    track: "interventional",
    kind: "direct",
    datePosted: "2026-09-17",
    need: "24-hour interventional call Wednesday–Monday or Friday–Monday.",
    setting: "Interventional cardiology 24-hour call",
    schedule: "Wednesday–Monday or Friday–Monday call blocks",
    call: "24-hour call during the selected block",
    metaTitle: "North-Central Minnesota IC Locum | 24-Hour Call",
    angle:
      "North-central Minnesota is offering 24-hour interventional call on Wednesday–Monday or Friday–Monday patterns—not the northeastern Minnesota two-week EP job. Minnesota licensure is still a full-license process for most out-of-state physicians.",
  },
  {
    slug: "michigan-northern-non-invasive-vms-locum",
    state: "Michigan",
    stateSlug: "michigan",
    region: "Northern Michigan",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in northern Michigan.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Northern Michigan Non-Invasive Cardiology Locum",
    angle:
      "This northern Michigan non-invasive row is a VMS posting: we can name the region and specialty, not the facility or a full schedule. Michigan is not an IMLC shortcut for most physicians, so license status is one of the first things we check.",
  },
  {
    slug: "vermont-north-central-non-invasive-vms-locum",
    state: "Vermont",
    stateSlug: "vermont",
    region: "North-central Vermont",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in north-central Vermont.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "North-Central Vermont Non-Invasive Cardiology Locum",
    angle:
      "North-central Vermont non-invasive coverage is listed with limited public detail. Vermont is not an IMLC member for most physicians, so an existing Vermont license—or a full-license timeline—usually decides whether this is near-term work.",
  },
  {
    slug: "wisconsin-western-non-invasive-vms-locum",
    state: "Wisconsin",
    stateSlug: "wisconsin",
    region: "Western Wisconsin",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in western Wisconsin.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Western Wisconsin Non-Invasive Cardiology Locum",
    angle:
      "Western Wisconsin non-invasive VMS coverage is a different geography than the east-central Wisconsin EP direct job. Public detail is limited; we confirm facility, dates, and whether the mix is clinic, hospital, or both after you inquire.",
  },
  {
    slug: "ohio-northeastern-non-invasive-vms-locum",
    state: "Ohio",
    stateSlug: "ohio",
    region: "Northeastern Ohio",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in northeastern Ohio.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "NE Ohio Non-Invasive Cardiology Locum | VMS",
    angle:
      "Northeastern Ohio non-invasive VMS work is not the featured Ohio interventional 1–2 weeks/month job and not the Cleveland-area non-invasive VMS row. Limited public detail is normal for vendor postings; we still need your licenses and dates to check whether it is open.",
  },
  {
    slug: "washington-northwestern-non-invasive-vms-locum",
    state: "Washington",
    stateSlug: "washington",
    region: "Northwestern Washington",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in northwestern Washington.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "NW Washington Non-Invasive Cardiology Locum",
    angle:
      "Northwestern Washington has both a non-invasive VMS row and a separate EP VMS row. This page is general/non-invasive only. We will not invent clinic volume or call rules; a consultant confirms those after you inquire.",
  },
  {
    slug: "ohio-cleveland-area-non-invasive-vms-locum",
    state: "Ohio",
    stateSlug: "ohio",
    region: "Cleveland area, Ohio",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in the Cleveland area.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Cleveland-Area Non-Invasive Cardiology Locum",
    angle:
      "Cleveland-area non-invasive VMS coverage is a different northeastern Ohio geography than the Canton-area non-invasive VMS row. Same specialty, different region—ask us to match the one that fits your travel radius.",
  },
  {
    slug: "alaska-southeastern-non-invasive-vms-locum",
    state: "Alaska",
    stateSlug: "alaska",
    region: "Southeastern Alaska",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in southeastern Alaska.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Southeastern Alaska Non-Invasive Cardiology Locum",
    angle:
      "Southeastern Alaska non-invasive locums usually turn on travel logistics and Alaska licensing as much as clinic skill. Public VMS detail is thin; we confirm whether the assignment is still posted and what travel support exists after you inquire.",
  },
  {
    slug: "illinois-southern-non-invasive-vms-locum",
    state: "Illinois",
    stateSlug: "illinois",
    region: "Southern Illinois",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in southern Illinois.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Southern Illinois Non-Invasive Cardiology Locum",
    angle:
      "Southern Illinois non-invasive VMS coverage is hospital-region work with limited public scope. If you already hold an Illinois license, we can usually check availability faster than a new-license timeline.",
  },
  {
    slug: "michigan-petoskey-area-non-invasive-vms-locum",
    state: "Michigan",
    stateSlug: "michigan",
    region: "Northern Michigan (Petoskey area)",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in the Petoskey area of northern Michigan.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Petoskey-Area Michigan Non-Invasive Cardiology Locum",
    angle:
      "This is the second northern Michigan non-invasive VMS row, tied to the Petoskey-area region rather than the other northern Michigan posting. Same specialty and state, different region—do not treat them as one job.",
  },
  {
    slug: "nebraska-southeastern-non-invasive-vms-locum",
    state: "Nebraska",
    stateSlug: "nebraska",
    region: "Southeastern Nebraska",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in southeastern Nebraska.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "SE Nebraska Non-Invasive Cardiology Locum",
    angle:
      "Southeastern Nebraska non-invasive VMS coverage is separate from the eastern Nebraska (Omaha-area) non-invasive VMS row. Share which Nebraska region you can actually travel to so we check the right posting.",
  },
  {
    slug: "nebraska-eastern-non-invasive-vms-locum",
    state: "Nebraska",
    stateSlug: "nebraska",
    region: "Eastern Nebraska",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in eastern Nebraska.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Eastern Nebraska Non-Invasive Cardiology Locum",
    angle:
      "Eastern Nebraska non-invasive VMS work is the Omaha-area region posting, not southeastern Nebraska. Vendor details stay private until we confirm the job is still open.",
  },
  {
    slug: "washington-kitsap-non-invasive-vms-locum",
    state: "Washington",
    stateSlug: "washington",
    region: "Western Washington (Kitsap)",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in the Kitsap region of western Washington.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Kitsap Washington Non-Invasive Cardiology Locum",
    angle:
      "Kitsap-region western Washington non-invasive VMS coverage is not the northwestern Washington non-invasive posting. Same state and specialty, different peninsula/region—travel time is not interchangeable.",
  },
  {
    slug: "south-carolina-coastal-non-invasive-vms-locum",
    state: "South Carolina",
    stateSlug: "south-carolina",
    region: "Coastal South Carolina",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system on the South Carolina coast.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Coastal SC Non-Invasive Cardiology Locum",
    angle:
      "Coastal South Carolina has a non-invasive VMS row and a separate interventional VMS row. This page is non-invasive only. We confirm whether the posting is still active after you inquire.",
  },
  {
    slug: "indiana-central-non-invasive-vms-locum",
    state: "Indiana",
    stateSlug: "indiana",
    region: "Central Indiana",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in central Indiana.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Central Indiana Non-Invasive Cardiology Locum",
    angle:
      "Central Indiana non-invasive VMS coverage is a different geography than the northern Indiana clinic-first direct job. Vendor postings stay thin on purpose; your license and dates let us check the live order.",
  },
  {
    slug: "west-virginia-western-non-invasive-vms-locum",
    state: "West Virginia",
    stateSlug: "west-virginia",
    region: "Western West Virginia",
    track: "non-invasive",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Non-invasive cardiology locum through a vendor system in western West Virginia.",
    setting: "Non-invasive cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "Call expectations confirmed with a consultant",
    metaTitle: "Western West Virginia Non-Invasive Cardiology Locum",
    angle:
      "Western West Virginia non-invasive VMS coverage is listed with limited public detail. We confirm the current facility, setting, and whether the order is still open after you inquire—without publishing a city name.",
  },
  {
    slug: "iowa-southeastern-interventional-vms-locum",
    state: "Iowa",
    stateSlug: "iowa",
    region: "Southeastern Iowa",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in southeastern Iowa.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "SE Iowa Interventional Cardiology Locum",
    angle:
      "Southeastern Iowa interventional VMS coverage cannot be described as a full cath-lab schedule on this page. Share PCI logs, licenses, and the weeks you can take so we can see if the vendor order is still live.",
  },
  {
    slug: "missouri-southeastern-interventional-vms-locum",
    state: "Missouri",
    stateSlug: "missouri",
    region: "Southeastern Missouri",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in southeastern Missouri.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "SE Missouri Interventional Cardiology Locum",
    angle:
      "Southeastern Missouri interventional VMS work is limited-detail vendor coverage. We will not guess STEMI backup or clinic mix; those come back from the consultant after you inquire.",
  },
  {
    slug: "south-carolina-coastal-interventional-vms-locum",
    state: "South Carolina",
    stateSlug: "south-carolina",
    region: "Coastal South Carolina",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system on the South Carolina coast.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "Coastal SC Interventional Cardiology Locum",
    angle:
      "Coastal South Carolina interventional VMS coverage is not the coastal non-invasive VMS job. Same region family, different specialty—PCI competency and call comfort are the first filters.",
  },
  {
    slug: "california-sacramento-area-interventional-vms-locum",
    state: "California",
    stateSlug: "california",
    region: "Northern California (Sacramento area)",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in the Sacramento area.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "Sacramento-Area Interventional Cardiology Locum",
    angle:
      "Sacramento-area interventional VMS coverage is a different California geography than the northwestern California direct call job and the San Joaquin Valley interventional VMS row. California licensing is a full-license process for most out-of-state physicians.",
  },
  {
    slug: "california-central-valley-interventional-vms-locum",
    state: "California",
    stateSlug: "california",
    region: "Central California (San Joaquin Valley)",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in the San Joaquin Valley.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "San Joaquin Valley Interventional Cardiology Locum",
    angle:
      "San Joaquin Valley interventional VMS coverage is central California, not the Sacramento-area interventional VMS posting. Same state and specialty, different region and vendor order.",
  },
  {
    slug: "florida-southwest-interventional-vms-locum",
    state: "Florida",
    stateSlug: "florida",
    region: "Southwest Florida",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in southwest Florida.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "Southwest Florida Interventional Cardiology Locum",
    angle:
      "Southwest Florida interventional VMS coverage is a different Florida geography than the south-central Florida direct interventional job. Vendor detail stays limited until we confirm the order is still available.",
  },
  {
    slug: "pennsylvania-south-central-interventional-vms-locum",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    region: "South-central Pennsylvania",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in south-central Pennsylvania.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "South-Central PA Interventional Cardiology Locum",
    angle:
      "South-central Pennsylvania interventional VMS coverage is not the northwestern Pennsylvania direct IC job, not the southwestern Pennsylvania holiday IC job, and not the northwestern Pennsylvania EP VMS row. Region and specialty both have to match.",
  },
  {
    slug: "pennsylvania-northwestern-interventional-vms-locum",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    region: "Northwestern Pennsylvania",
    track: "interventional",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Interventional cardiology locum through a vendor system in northwestern Pennsylvania.",
    setting: "Interventional cardiology (details confirmed privately)",
    schedule: "Dates and shift length confirmed with a consultant",
    call: "STEMI and call rules confirmed with a consultant",
    metaTitle: "NW Pennsylvania Interventional Cardiology Locum | VMS",
    angle:
      "Northwestern Pennsylvania has a direct interventional job (call plus scheduled hours) and this separate interventional VMS posting. Do not treat them as the same order. The VMS page stays limited until a consultant confirms it is still open.",
  },
  {
    slug: "washington-northwestern-ep-vms-locum",
    state: "Washington",
    stateSlug: "washington",
    region: "Northwestern Washington",
    track: "electrophysiology",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Electrophysiology locum through a vendor system in northwestern Washington.",
    setting: "Electrophysiology (details confirmed privately)",
    schedule: "Dates and lab mix confirmed with a consultant",
    call: "EP call expectations confirmed with a consultant",
    metaTitle: "NW Washington Electrophysiology Locum",
    angle:
      "Northwestern Washington EP VMS coverage is not the northwestern Washington non-invasive VMS job. Ablation and device privileges are the usual gates; we confirm the live vendor scope after you inquire.",
  },
  {
    slug: "pennsylvania-northwestern-ep-vms-locum",
    state: "Pennsylvania",
    stateSlug: "pennsylvania",
    region: "Northwestern Pennsylvania",
    track: "electrophysiology",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Electrophysiology locum through a vendor system in northwestern Pennsylvania.",
    setting: "Electrophysiology (details confirmed privately)",
    schedule: "Dates and lab mix confirmed with a consultant",
    call: "EP call expectations confirmed with a consultant",
    metaTitle: "NW Pennsylvania Electrophysiology Locum",
    angle:
      "Northwestern Pennsylvania EP VMS coverage is not the northwestern Pennsylvania interventional direct job. Same region family, electrophysiology only. Lab volume and device follow-up stay private until we confirm availability.",
  },
  {
    slug: "ohio-northeastern-ep-vms-locum",
    state: "Ohio",
    stateSlug: "ohio",
    region: "Northeastern Ohio",
    track: "electrophysiology",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Electrophysiology locum through a vendor system in northeastern Ohio.",
    setting: "Electrophysiology (details confirmed privately)",
    schedule: "Dates and lab mix confirmed with a consultant",
    call: "EP call expectations confirmed with a consultant",
    metaTitle: "NE Ohio Electrophysiology Locum",
    angle:
      "Northeastern Ohio EP VMS coverage is not the northeastern Ohio non-invasive VMS row and not the featured Ohio interventional locum. EP privileges and recent case volume are what we need to check the vendor order.",
  },
  {
    slug: "oregon-western-ep-vms-locum",
    state: "Oregon",
    stateSlug: "oregon",
    region: "Western Oregon",
    track: "electrophysiology",
    kind: "vms",
    datePosted: "2026-09-29",
    need: "Electrophysiology locum through a vendor system in western Oregon.",
    setting: "Electrophysiology (details confirmed privately)",
    schedule: "Dates and lab mix confirmed with a consultant",
    call: "EP call expectations confirmed with a consultant",
    metaTitle: "Western Oregon Electrophysiology Locum",
    angle:
      "Western Oregon EP VMS coverage is limited-detail vendor work. Oregon is not an IMLC shortcut for most physicians, so license status is usually the first filter before we ask a consultant whether the order is still posted.",
  },
];
