/** US metros / cities for cardiologist locum programmatic pages. */
export type CardiologyMetro = {
  city: string;
  state: string;
  stateSlug: string;
};

function slugPart(s: string): string {
  return s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function metroSlug(m: CardiologyMetro): string {
  return `cardiologist-locum-jobs-${slugPart(m.city)}-${m.stateSlug}`;
}

export const CARDIOLOGY_METROS: CardiologyMetro[] = [
  { city: "New York", state: "NY", stateSlug: "new-york" },
  { city: "Los Angeles", state: "CA", stateSlug: "california" },
  { city: "Chicago", state: "IL", stateSlug: "illinois" },
  { city: "Houston", state: "TX", stateSlug: "texas" },
  { city: "Phoenix", state: "AZ", stateSlug: "arizona" },
  { city: "Philadelphia", state: "PA", stateSlug: "pennsylvania" },
  { city: "San Antonio", state: "TX", stateSlug: "texas" },
  { city: "San Diego", state: "CA", stateSlug: "california" },
  { city: "Dallas", state: "TX", stateSlug: "texas" },
  { city: "Jacksonville", state: "FL", stateSlug: "florida" },
  { city: "Austin", state: "TX", stateSlug: "texas" },
  { city: "San Jose", state: "CA", stateSlug: "california" },
  { city: "Fort Worth", state: "TX", stateSlug: "texas" },
  { city: "Columbus", state: "OH", stateSlug: "ohio" },
  { city: "Charlotte", state: "NC", stateSlug: "north-carolina" },
  { city: "Indianapolis", state: "IN", stateSlug: "indiana" },
  { city: "San Francisco", state: "CA", stateSlug: "california" },
  { city: "Seattle", state: "WA", stateSlug: "washington" },
  { city: "Denver", state: "CO", stateSlug: "colorado" },
  { city: "Nashville", state: "TN", stateSlug: "tennessee" },
  { city: "Oklahoma City", state: "OK", stateSlug: "oklahoma" },
  { city: "Boston", state: "MA", stateSlug: "massachusetts" },
  { city: "El Paso", state: "TX", stateSlug: "texas" },
  { city: "Detroit", state: "MI", stateSlug: "michigan" },
  { city: "Portland", state: "OR", stateSlug: "oregon" },
  { city: "Las Vegas", state: "NV", stateSlug: "nevada" },
  { city: "Memphis", state: "TN", stateSlug: "tennessee" },
  { city: "Louisville", state: "KY", stateSlug: "kentucky" },
  { city: "Baltimore", state: "MD", stateSlug: "maryland" },
  { city: "Milwaukee", state: "WI", stateSlug: "wisconsin" },
  { city: "Albuquerque", state: "NM", stateSlug: "new-mexico" },
  { city: "Tucson", state: "AZ", stateSlug: "arizona" },
  { city: "Fresno", state: "CA", stateSlug: "california" },
  { city: "Sacramento", state: "CA", stateSlug: "california" },
  { city: "Atlanta", state: "GA", stateSlug: "georgia" },
  { city: "Miami", state: "FL", stateSlug: "florida" },
  { city: "Tampa", state: "FL", stateSlug: "florida" },
  { city: "Orlando", state: "FL", stateSlug: "florida" },
  { city: "Cleveland", state: "OH", stateSlug: "ohio" },
  { city: "Minneapolis", state: "MN", stateSlug: "minnesota" },
  { city: "Kansas City", state: "MO", stateSlug: "missouri" },
  { city: "Raleigh", state: "NC", stateSlug: "north-carolina" },
  { city: "Omaha", state: "NE", stateSlug: "nebraska" },
  { city: "Colorado Springs", state: "CO", stateSlug: "colorado" },
  { city: "Virginia Beach", state: "VA", stateSlug: "virginia" },
  { city: "Oakland", state: "CA", stateSlug: "california" },
  { city: "Tulsa", state: "OK", stateSlug: "oklahoma" },
  { city: "Arlington", state: "TX", stateSlug: "texas" },
  { city: "New Orleans", state: "LA", stateSlug: "louisiana" },
  { city: "Wichita", state: "KS", stateSlug: "kansas" },
  { city: "Bakersfield", state: "CA", stateSlug: "california" },
  { city: "Honolulu", state: "HI", stateSlug: "hawaii" },
  { city: "Anaheim", state: "CA", stateSlug: "california" },
  { city: "Santa Ana", state: "CA", stateSlug: "california" },
  { city: "Riverside", state: "CA", stateSlug: "california" },
  { city: "St. Louis", state: "MO", stateSlug: "missouri" },
  { city: "Corpus Christi", state: "TX", stateSlug: "texas" },
  { city: "Lexington", state: "KY", stateSlug: "kentucky" },
  { city: "Pittsburgh", state: "PA", stateSlug: "pennsylvania" },
  { city: "Anchorage", state: "AK", stateSlug: "alaska" },
  { city: "Stockton", state: "CA", stateSlug: "california" },
  { city: "Cincinnati", state: "OH", stateSlug: "ohio" },
  { city: "St. Paul", state: "MN", stateSlug: "minnesota" },
  { city: "Toledo", state: "OH", stateSlug: "ohio" },
  { city: "Newark", state: "NJ", stateSlug: "new-jersey" },
  { city: "Greensboro", state: "NC", stateSlug: "north-carolina" },
  { city: "Plano", state: "TX", stateSlug: "texas" },
  { city: "Henderson", state: "NV", stateSlug: "nevada" },
  { city: "Lincoln", state: "NE", stateSlug: "nebraska" },
  { city: "Buffalo", state: "NY", stateSlug: "new-york" },
  { city: "Fort Wayne", state: "IN", stateSlug: "indiana" },
  { city: "Jersey City", state: "NJ", stateSlug: "new-jersey" },
  { city: "St. Petersburg", state: "FL", stateSlug: "florida" },
  { city: "Chula Vista", state: "CA", stateSlug: "california" },
  { city: "Norfolk", state: "VA", stateSlug: "virginia" },
  { city: "Chandler", state: "AZ", stateSlug: "arizona" },
  { city: "Laredo", state: "TX", stateSlug: "texas" },
  { city: "Madison", state: "WI", stateSlug: "wisconsin" },
  { city: "Durham", state: "NC", stateSlug: "north-carolina" },
  { city: "Lubbock", state: "TX", stateSlug: "texas" },
  { city: "Winston-Salem", state: "NC", stateSlug: "north-carolina" },
  { city: "Garland", state: "TX", stateSlug: "texas" },
  { city: "Glendale", state: "AZ", stateSlug: "arizona" },
  { city: "Hialeah", state: "FL", stateSlug: "florida" },
  { city: "Reno", state: "NV", stateSlug: "nevada" },
  { city: "Baton Rouge", state: "LA", stateSlug: "louisiana" },
  { city: "Irvine", state: "CA", stateSlug: "california" },
  { city: "Chesapeake", state: "VA", stateSlug: "virginia" },
  { city: "Irving", state: "TX", stateSlug: "texas" },
  { city: "Scottsdale", state: "AZ", stateSlug: "arizona" },
  { city: "North Las Vegas", state: "NV", stateSlug: "nevada" },
  { city: "Fremont", state: "CA", stateSlug: "california" },
  { city: "Gilbert", state: "AZ", stateSlug: "arizona" },
  { city: "San Bernardino", state: "CA", stateSlug: "california" },
  { city: "Boise", state: "ID", stateSlug: "idaho" },
  { city: "Birmingham", state: "AL", stateSlug: "alabama" },
  { city: "Rochester", state: "NY", stateSlug: "new-york" },
  { city: "Richmond", state: "VA", stateSlug: "virginia" },
  { city: "Spokane", state: "WA", stateSlug: "washington" },
  { city: "Des Moines", state: "IA", stateSlug: "iowa" },
  { city: "Montgomery", state: "AL", stateSlug: "alabama" },
  { city: "Modesto", state: "CA", stateSlug: "california" },
  { city: "Fayetteville", state: "NC", stateSlug: "north-carolina" },
  { city: "Tacoma", state: "WA", stateSlug: "washington" },
  { city: "Shreveport", state: "LA", stateSlug: "louisiana" },
  { city: "Akron", state: "OH", stateSlug: "ohio" },
  { city: "Mobile", state: "AL", stateSlug: "alabama" },
  { city: "Little Rock", state: "AR", stateSlug: "arkansas" },
  { city: "Augusta", state: "GA", stateSlug: "georgia" },
  { city: "Grand Rapids", state: "MI", stateSlug: "michigan" },
  { city: "Salt Lake City", state: "UT", stateSlug: "utah" },
  { city: "Huntsville", state: "AL", stateSlug: "alabama" },
  { city: "Knoxville", state: "TN", stateSlug: "tennessee" },
  { city: "Worcester", state: "MA", stateSlug: "massachusetts" },
  { city: "Newport News", state: "VA", stateSlug: "virginia" },
  { city: "Brownsville", state: "TX", stateSlug: "texas" },
  { city: "Providence", state: "RI", stateSlug: "rhode-island" },
  { city: "Santa Clarita", state: "CA", stateSlug: "california" },
  { city: "Fort Lauderdale", state: "FL", stateSlug: "florida" },
  { city: "Chattanooga", state: "TN", stateSlug: "tennessee" },
  { city: "Tempe", state: "AZ", stateSlug: "arizona" },
  { city: "Oceanside", state: "CA", stateSlug: "california" },
  { city: "Garden Grove", state: "CA", stateSlug: "california" },
  { city: "Rancho Cucamonga", state: "CA", stateSlug: "california" },
  { city: "Cape Coral", state: "FL", stateSlug: "florida" },
  { city: "Santa Rosa", state: "CA", stateSlug: "california" },
  { city: "Vancouver", state: "WA", stateSlug: "washington" },
  { city: "Sioux Falls", state: "SD", stateSlug: "south-dakota" },
  { city: "Peoria", state: "AZ", stateSlug: "arizona" },
  { city: "Ontario", state: "CA", stateSlug: "california" },
  { city: "Jackson", state: "MS", stateSlug: "mississippi" },
  { city: "Elk Grove", state: "CA", stateSlug: "california" },
  { city: "Springfield", state: "MO", stateSlug: "missouri" },
  { city: "Pembroke Pines", state: "FL", stateSlug: "florida" },
  { city: "Salem", state: "OR", stateSlug: "oregon" },
  { city: "Eugene", state: "OR", stateSlug: "oregon" },
  { city: "Corona", state: "CA", stateSlug: "california" },
  { city: "McKinney", state: "TX", stateSlug: "texas" },
  { city: "Fort Collins", state: "CO", stateSlug: "colorado" },
  { city: "Lancaster", state: "CA", stateSlug: "california" },
  { city: "Cary", state: "NC", stateSlug: "north-carolina" },
  { city: "Palmdale", state: "CA", stateSlug: "california" },
  { city: "Hayward", state: "CA", stateSlug: "california" },
  { city: "Salinas", state: "CA", stateSlug: "california" },
  { city: "Frisco", state: "TX", stateSlug: "texas" },
  { city: "Springfield", state: "MA", stateSlug: "massachusetts" },
  { city: "Pasadena", state: "TX", stateSlug: "texas" },
  { city: "Macon", state: "GA", stateSlug: "georgia" },
  { city: "Alexandria", state: "VA", stateSlug: "virginia" },
  { city: "Pomona", state: "CA", stateSlug: "california" },
  { city: "Lakewood", state: "CO", stateSlug: "colorado" },
  { city: "Sunnyvale", state: "CA", stateSlug: "california" },
  { city: "Escondido", state: "CA", stateSlug: "california" },
  { city: "Kansas City", state: "KS", stateSlug: "kansas" },
  { city: "Hollywood", state: "FL", stateSlug: "florida" },
  { city: "Clarksville", state: "TN", stateSlug: "tennessee" },
  { city: "Torrance", state: "CA", stateSlug: "california" },
  { city: "Rockford", state: "IL", stateSlug: "illinois" },
  { city: "Joliet", state: "IL", stateSlug: "illinois" },
  { city: "Paterson", state: "NJ", stateSlug: "new-jersey" },
  { city: "Bridgeport", state: "CT", stateSlug: "connecticut" },
  { city: "Naperville", state: "IL", stateSlug: "illinois" },
  { city: "Savannah", state: "GA", stateSlug: "georgia" },
  { city: "Mesquite", state: "TX", stateSlug: "texas" },
  { city: "Syracuse", state: "NY", stateSlug: "new-york" },
  { city: "Pasadena", state: "CA", stateSlug: "california" },
  { city: "Orange", state: "CA", stateSlug: "california" },
  { city: "Fullerton", state: "CA", stateSlug: "california" },
  { city: "Killeen", state: "TX", stateSlug: "texas" },
  { city: "Dayton", state: "OH", stateSlug: "ohio" },
  { city: "McAllen", state: "TX", stateSlug: "texas" },
  { city: "Bellevue", state: "WA", stateSlug: "washington" },
  { city: "Metairie", state: "LA", stateSlug: "louisiana" },
  { city: "Columbia", state: "SC", stateSlug: "south-carolina" },
  { city: "Olathe", state: "KS", stateSlug: "kansas" },
  { city: "Carrollton", state: "TX", stateSlug: "texas" },
  { city: "Midland", state: "TX", stateSlug: "texas" },
  { city: "Charleston", state: "SC", stateSlug: "south-carolina" },
  { city: "Waco", state: "TX", stateSlug: "texas" },
  { city: "Sterling Heights", state: "MI", stateSlug: "michigan" },
  { city: "Denton", state: "TX", stateSlug: "texas" },
  { city: "New Haven", state: "CT", stateSlug: "connecticut" },
  { city: "Thousand Oaks", state: "CA", stateSlug: "california" },
  { city: "Concord", state: "CA", stateSlug: "california" },
  { city: "Visalia", state: "CA", stateSlug: "california" },
  { city: "Simi Valley", state: "CA", stateSlug: "california" },
  { city: "Hartford", state: "CT", stateSlug: "connecticut" },
  { city: "Green Bay", state: "WI", stateSlug: "wisconsin" },
  { city: "Columbia", state: "MO", stateSlug: "missouri" },
  { city: "Abilene", state: "TX", stateSlug: "texas" },
  { city: "Wilmington", state: "DE", stateSlug: "delaware" },
  { city: "Ann Arbor", state: "MI", stateSlug: "michigan" },
  { city: "Provo", state: "UT", stateSlug: "utah" },
  { city: "Lansing", state: "MI", stateSlug: "michigan" },
  { city: "Evansville", state: "IN", stateSlug: "indiana" },
  { city: "Manchester", state: "NH", stateSlug: "new-hampshire" },
  { city: "Fargo", state: "ND", stateSlug: "north-dakota" },
  { city: "Billings", state: "MT", stateSlug: "montana" },
  { city: "Cheyenne", state: "WY", stateSlug: "wyoming" },
  { city: "Burlington", state: "VT", stateSlug: "vermont" },
  { city: "Charleston", state: "WV", stateSlug: "west-virginia" },
  { city: "Portland", state: "ME", stateSlug: "maine" },
  { city: "Wilmington", state: "NC", stateSlug: "north-carolina" },
  { city: "Washington", state: "DC", stateSlug: "district-of-columbia" },
];
